cleaned up install script and added dependencies. see quaxlyqueen/scripts for check-dependency script.

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,6 +7,22 @@ if [[ $EUID -ne 0 ]]; then
     exit 1
 fi
 
+# Check if the required packages are installed
+echo "Checking for required packages..."
+
+# Iterate through each line of the dependencies.txt file
+# and check if the package is installed with check-dependency <command> <package>
+while read -r line; do
+    command=$(echo $line | awk '{print $1}')
+    package=$(echo $line | awk '{print $2}')
+
+    if [[ check-dependency $command $package -eq 1 ]]; then
+        echo "The package $package could not be installed. Please install it before continuing."
+        exit 1
+    fi
+
+done < dependencies.txt
+
 echo "Installing the system tray onto your system..."
 
 # Get the current working directory and the virtual environment
